### ISSUE TITLE
SMTP Fails to send through selected SMTP rather sends through localhost

### ISSUE THREAD

**Issue by rtokarchyk** [orocrm/platform#437] opened 2016-04-06 03:39 UTC
For some reason, when we try to setup STMP, we get an SMTP failed error.  When our admin checks the server he sees that the application is connecting to localhost rather than to the selected office365 smtp server.

The server log shows the following:

SMTP connection from [108.52.239.21]:35468 (TCP/IP connection count = 1)
2016-04-01 13:05:51 dovecot_login authenticator failed for static-108-52-239-21.phlapa.fios.verizon.net (crm.xxxxxxxxxx) [108.52.239.21]:35468: 535 Incorrect authentication data (set_id=email@xxxxxxxxxxxxxx)
2016-04-01 13:05:57 dovecot_plain authenticator failed for static-108-52-239-21.phlapa.fios.verizon.net (crm.xxxxxxxxxx) [108.52.239.21]:35468: 535 Incorrect authentication data (set_id=email@xxxxxxxxxxx)
2016-04-01 13:05:57 SMTP connection from static-108-52-239-21.phlapa.fios.verizon.net (crm.xxxxxxxxxxxxxxx) [108.52.239.21]:35468 lost
2016-04-01 13:07:27 SMTP connection from [108.52.239.21]:36097 (TCP/IP connection count = 1)

Does anybody have an idea what could be causing this?

**Comment by DimaSoroka** [comment] 2016-04-06 17:19
Please describe how you are trying to do this setup and where error occurs.

**Comment by rtokarchyk** [comment] 2016-04-06 17:54
This error occurs when I go to my emails and send an email.  It give the SMTP Failed Error, then we check the logs and that is what is happening.

My admin says that ORO is sending emails through localhost rather then using the SMTP settings.

Are you able to login and help seewhy this is happening.?

**Comment by DimaSoroka** [comment] 2016-04-06 18:09
Did you update smtp configuration in parameters.yml?

**Comment by rtokarchyk** [comment] 2016-04-06 18:10
We just updated it in the UI user settings.

**Comment by rtokarchyk** [comment] 2016-04-06 18:11
Should we update in the parameters.yml.   Do i have to do that one time, or do it one time?

**Comment by DimaSoroka** [comment] 2016-04-06 18:13
There are two parts: global SMTP configuration in the parameters.yml for all the emails sent from application and user configuration in the user profile for personal emails in case user wants to get them in the original mailbox "sent" folder

**Comment by rtokarchyk** [comment] 2016-04-06 18:31
OK,  can you send me what we need to change so the SMTP uses our company SMTP server?  Do you have a document on it?

**Comment by rtokarchyk** [comment] 2016-04-06 18:33
So you are saying the parameters.yml overides the USER settings SMTP settings that we set?

**Comment by rtokarchyk** [comment] 2016-04-06 18:34
Our Emails are syncing, but the SMTP does not work.

**Comment by DimaSoroka** [comment] 2016-04-06 18:39
No, opposite, user SMTP configuration overrides system one in user session,

**Comment by rtokarchyk** [comment] 2016-04-06 18:40
OK well we have the SMTP Settings set for the user and he is unable to send emails.  It throws that error. Are you able to hop on our system and see?

**Comment by rtokarchyk** [comment] 2016-04-06 19:23
This does not make sense why the issue is happening.  I would like to get this corrected so we can effectively use the system

**Comment by rtokarchyk** [comment] 2016-04-06 19:26
You can see from the log below that is does now use the predefined User SMTP Setting


![image](https://cloud.githubusercontent.com/assets/18299315/14329929/e336ec6e-fc0b-11e5-9338-22a1604c10e2.png)


MTP connection from [108.52.239.21]:35468 (TCP/IP connection count = 1)
2016-04-01 13:05:51 dovecot_login authenticator failed for static-108-52-239-21.phlapa.fios.verizon.net (crm.xxxxxxxxxx) [108.52.239.21]:35468: 535 Incorrect authentication data (set_id=email@xxxxxxxxxxxxxx)
2016-04-01 13:05:57 dovecot_plain authenticator failed for static-108-52-239-21.phlapa.fios.verizon.net (crm.xxxxxxxxxx) [108.52.239.21]:35468: 535 Incorrect authentication data (set_id=email@xxxxxxxxxxx)
2016-04-01 13:05:57 SMTP connection from static-108-52-239-21.phlapa.fios.verizon.net (crm.xxxxxxxxxxxxxxx) [108.52.239.21]:35468 lost
2016-04-01 13:07:27 SMTP connection from [108.52.239.21]:36097 (TCP/IP connection count = 1)

**Comment by rtokarchyk** [comment] 2016-04-06 19:27
This is what we do to get the Server error

![image](https://cloud.githubusercontent.com/assets/18299315/14329959/101707b4-fc0c-11e5-9b50-57e86b1ed203.png)

**Comment by DimaSoroka** [comment] 2016-04-06 19:29
Please feel free to investigate root cause and provide more details or PR with fix, we do have support options for enterprise edition if you are interested.

**Comment by rtokarchyk** [comment] 2016-04-06 21:24
Im confused.  Are you saying that this is our servers issue?  Or is it your application?   Do you have documentation on the Server Configuration setup regarding the email server.

**Comment by DimaSoroka** [comment] 2016-04-06 22:22
The issue most likely is with connection to SMTP.

**Comment by rtokarchyk** [comment] 2016-04-08 03:05
OK,  We solved the SMTP issue.  There was an issue with WHM where it had a setting that blocked SMTP emails.  We turned it off and that corrected it

**Comment by rtokarchyk** [comment] 2016-04-08 03:07
We got the email working, but i am curious.  It seems that the first type i synced the emails, the emails synced for that day.   It has been 2 days later, and when i hit sync on email, there are no more emails being added to the unread folder.

Is there somethign we are missing to do here.

**Comment by rtokarchyk** [comment] 2016-04-08 03:07
Here is a screen shot 

![image](https://cloud.githubusercontent.com/assets/18299315/14373199/76db2f84-fd15-11e5-8294-41e5d6eb025b.png)

**Comment by artml** [comment] 2016-08-05 15:06
@rtokarchyk have your daemon been running? (if the issue still stands of course)

**Comment by mkudelya** [comment] 2017-02-10 12:17
@rtokarchyk 

I’m closing this issue as we have not received feedback from you. Feel free open it if you have any question.

**Closed by mkudelya** 2017-02-10 12:17 UTC
Labels: bug, feedback needed
