### ISSUE TITLE
How to hide dynamic column from datagrid?

### ISSUE THREAD

**Issue by kusgpt26** [orocrm/platform#715] opened 2017-06-22 05:54 UTC
I have an installation of OROCRM 2.0. I have created an entity Asset than mapped asset with Account Bundle with migration.

```
class AccountMaptoAsset implements Migration, ExtendExtensionAwareInterface
{
  protected $extendExtension;

  public function setExtendExtension(ExtendExtension $extendExtension)
  {
      $this->extendExtension = $extendExtension;
  }

  public function up(Schema $schema, QueryBag $queries)
  {
      $this->extendExtension->addManyToOneRelation(
          $schema,
          'hotelivate_asset', // owning side table
          'account', // owning side field name
          'orocrm_account', // inverse side table
          'name', // column name is used to show related entity
          ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
      );
      $this->extendExtension->addManyToOneInverseRelation(
          $schema,
          'hotelivate_asset', // owning side table
          'account', // owning side field name
          'orocrm_account', // inverse side table
          'assets', // inverse side field name
          ['name'], // column names are used to show a title of owning side entity
          ['name'], // column names are used to show detailed info about owning side entity
          ['name'], // Column names are used to show owning side entity in a grid
          ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
      );
  }
}

```

All things working properly and in  datagrid a column named `ACCOUNT`  automatic appears according to migration. 

But i want to hide or remove this column `ACCOUNT` from my datagrid. I don't understand how to do this beacuse in `datagrids.yml`  file i have not written any line of code to show this column.

Is there are any way to handle this? Please Reply if any possibility to do this.

**Comment by d-beekeeper** [comment] 2017-06-23 09:47
Hi, kusgpt26
Yes, you can achieve this using datagrid event listeners.
You need to create your own listener for your datagrid and add option "'renderable' => false" to column 'ACCOUNT'
Please take a look at this example:
https://github.com/orocommerce/orocommerce/blob/master/src/Oro/Bundle/TaxBundle/EventListener/CustomerTaxCodeGridListener.php#L16
Although it is from orocommerce, in this case it doesnt matter.

**Comment by alex-n-2k7** [comment] 2017-07-18 19:08
Hi @kusgpt26,
Please, have a look at this https://github.com/orocrm/crm/issues/279

**Comment by aivus** [comment] 2017-07-21 08:05
Duplicate of orocrm/crm#279

**Closed by aivus** 2017-07-21 08:05 UTC
Labels: duplicate, feedback needed, question
