### ISSUE TITLE
Regular Entity and UI

### ISSUE THREAD

**Issue by yoocloud** [orocrm/platform#250] opened 2015-04-09 17:39 UTC
How to register as an regular entity to appear in the reporting list? Created a regular entity and migration but does not appear in the UI entities.

Thanks.
![1](https://cloud.githubusercontent.com/assets/10473169/7072928/495b58d6-dec6-11e4-8ca3-6869bd50f499.jpg)

**Comment by vsoroka** [comment] 2015-04-10 17:16
Hello @kzweb,

The entity management page as well as other pages like email templates, reports, workflows show only configurable entities. To make entity configurable you can use \@Config annotation. Simple example you can see in https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/TaskBundle/Entity/TaskPriority.php#L13, or in https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/TaskBundle/Entity/Task.php#L32-L71 for more advanced configuration

**Comment by kzweb** [comment] 2015-04-11 03:11
It's not a bug. Added the annotation and run update: php app/console oro:entity-config:update

Please, close this issue.

**Comment by kzweb** [comment] 2015-04-11 03:11
It's not a bug. Added the annotation and run update: php app/console oro:entity-config:update

Please, close this issue.

**Closed** 2015-04-13 15:27 UTC
