### ISSUE TITLE
Cannot save oneToMany fields on Custom entity forms

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#200] opened 2014-12-03 16:15 UTC
I have tested this scenario locally and today on the oro demo:
1. Create an entity called testA (update schema)
2. Create an entity called testB with a manyToOne relationship to testA (update schema)
3. Add the opposite relationship (oneToMany) into testA with the "Reuse ..." field type (update schema)
4. Create a testB instance
5. Create a testA instance and try and associate the testB instance in the form (with the add button that pops up the testB datagrid)

The problem seems to be that the generated custom entity for testA will have getters and setters for testB's but not an addTestB method which is what the form system is going to call to add the testB instance.

```
Fatal error: Call to undefined method Extend\Entity\testA::addTestB() in /vagrant/vendor/oro/platform/src/Oro/Bundle/EntityConfigBundle/Tools/FieldAccessor.php on line 42
```

I am running 1.4.1.  I have not checked 1.4.2 yet unless that is running the demo @ demo.orocrm.com, in which case I have tried it given I managed to get this error today on the demo site

Cheers guys
Luke

**Comment by LRotherfield** [comment] 2017-01-18 17:52
@vsoroka do you know if this was fixed, it is super old and I have not tested recently.  I will test in a bit if you have not responded

**Comment by mkudelya** [comment] 2017-02-08 14:45
Hi @LRotherfield 

I have tested your case on 1.10.14 and 2.0.1 versions and i can't reproduce issue. I'm closing this issue, feel free to open if you have any questions.

**Closed by mkudelya** 2017-02-08 14:45 UTC
Labels: bug, open for contribution
