### ISSUE TITLE
Boostrap ScrollSpy Chrome Display Bug

### ISSUE THREAD

**Issue by ghost** [orocrm/platform#342] opened 2015-11-11 16:01 UTC
Hi Guys,

we found a Chrome Display Bug on Pages which uses the Boostrap ScrollSpy Module.
When you Click on an anchor Tag in the Menu, you will stick to this Content an can not scroll out.
You can reproduce the Bug on the ORO CRM Demo-Page.
Go to an Account, Click on "Additional Information" and try so scroll up with the mouse wheel.

ORO CRM Version 1.6.1 and ORO CRM Demo-Page
Chrome Version 46.0.2490.80
Mac OS X Version 10.11.1

Can you take a look at this?

Thanks and regards, David

**Comment by stepansib** [comment] 2015-11-13 00:48
Yes, i faced the same bug. Appears in Chrome, FF, Opera.
OroBAP 1.8.2

**Comment by stepansib** [comment] 2015-11-13 08:32
Sorry, in FF 41.0.2 everything is ok.
But this bug still appears in Chrome

**Comment by artml** [comment] 2016-08-05 14:23
@stepansib does it reproduce at 1.9 or 1.10 master?

**Comment by artml** [comment] 2016-10-18 14:05
closing due to no feedback

**Closed by artml** 2016-10-18 14:05 UTC
Labels: bug, feedback needed
