### ISSUE TITLE
Non-default "Items Per Page" hangs data grid when changing grid view

### ISSUE THREAD

**Issue by cmenning** [orocrm/platform#395] opened 2016-02-10 18:01 UTC
In System --> Configuration --> General setup --> Display settings, changing the "Items Per Page By Default" option under Data Grid Settings causes the data grid to hang when changing grid views. To duplicate:

1. Change the setting mentioned above to something non-default (say, 100).
2. Browse to a data grid (say, Sales --> Leads).
3. Click the "All Leads" grid view to something else (create one first, if needed).
4. Watch as the new leads are loaded and displayed, but the progress spinner never quits and the View Per Page remains greyed out. 

At this point, checking the console reveals an error message along the lines of:

```TypeError: currentSizeLabel[0] is undefined```

Returning the option mentioned above to the default value fixes the data grid display.

**Comment by Grygir** [comment] 2016-02-11 09:48
Hi @cmenning,

Can not reproduce this issue in the latest version of OroPlatform. It looks like the issue is already fixed there: [page-size.js (v1.9)](https://github.com/orocrm/platform/blob/1.9/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/page-size.js#L119-L124) and [page-size.js (v1.8)](https://github.com/orocrm/platform/blob/1.8/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/page-size.js#L120-L121)

What version of platform do you use? We will port the fix in older versions.

**Comment by cmenning** [comment] 2016-02-11 14:25
@Grygir,

We're using 1.8.2. I didn't notice the change in [1.9](https://github.com/orocrm/platform/blob/1.9/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/page-size.js#L119-L124) and saw that the filter logic was the same. Thanks!

**Comment by Grygir** [comment] 2016-02-11 14:35
The issue will be fixed in 1.8.* with release 1.8.3

**Comment by Grygir** [comment] 2016-02-18 10:31
The is fixed in master branch.

**Closed by Grygir** 2016-02-18 10:31 UTC
