### ISSUE TITLE
Multiple datagrids with the same name render the data of the first one

### ISSUE THREAD

**Issue by dragulceo** [orocrm/platform#223] opened 2015-01-30 03:03 UTC
In one window there are shown multiple items from one entity. 
The entity has attachments so for each item we display the `attachment-grid` through the `view_content_data_additional_information` placeholder.

Surprisingly (for me) this kind of works in that for each item there is an attachment grid rendered.
The only issue is that the data displayed in all the grids is the data of the first grid.

I investigated this issue and found out that there is a [Backbone collection caching system](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/public/js/content-manager.js#L21) that uses as a [key for cache the name of the grid](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/public/js/app/components/datagrid-component.js#L140) (which for all the grids is `attachment-grid`). 

So for my case I overwrite the datagrid-component.js and compose the cache key with the widget id.

Even though I'm not sure that this is an important issue with the datagrid (because the situation I stumbled upon is rare) I still wanted to notify you of it's existence. If you do agree with me and consider it an issue and decide that you want it resolved I can make a pull request with a fix for it.

The fix I propose is to use the grid id as a key for the cache instead of the grid name or concatenate the grid id to the grid name.

**Comment by dragulceo** [comment] 2015-01-30 03:18
Here is a visual example:

## Before

![Before](http://i.imgur.com/j1wfXGs.png)

## After

![After](http://i.imgur.com/EHQLKk1.png)

**Comment by yurio** [comment] 2015-02-19 18:30
Hi, @dragulceo.
Thanks for your request. 
Please make PR, I think this is an interesting issue and if your fix is correct, we can merge it to core code.

**Comment by akuzmenko-magecore** [comment] 2015-05-18 14:22
Hi @dragulceo,
I've answered in your pull request. Will `oro_datagrid_build_fullname` twig function help your issue?

**Comment by dragulceo** [comment] 2015-05-18 16:02
No. The attachment widget is rendered in a complicated way and to me it seemed more difficult to pass a unique name rather than disable the caching. 

Long time has passed since then so I don't remember exactly the complication but I know for that I could not pass easily a custom grid name. (I looked a little at the code to refresh my memory and it is not easy to understand how the attachment grid appears: it's coming from a placeholder which outputs a js widget which then renders the grid).

However I admit that this may not be an issue with the datagrid but that is why I started this discussion.

While we are discussing let me point out also that when multiple grids are visible they were not in sync (even though they load from the same cached data). So if I remember correctly when I uploaded a file only one datagrid was refreshing the others were still.

**Comment by Grygir** [comment] 2015-08-21 14:23
Please see [DataGrid Scope](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/doc/backend/scopes.md) and `oro_datagrid_build_fullname` helper documentation. It looks like it is best solution for your case.

**Comment by amontemaggio** [comment] 2015-10-04 13:51
Hi there, in my case using datagrid scope solved the data caching problem, but what I see is that the scope seems to be ignored in the construction of the request on filter update event. So, this solution could not be considered valid for datagrid using filters.

**Comment by Grygir** [comment] 2015-10-05 15:20
Hi @amontemaggio 

This is a bug in scope implementation. Thank you for pointing out. We will it in coming release.

**Comment by amontemaggio** [comment] 2015-10-05 16:19
This morning we solved this issue by overriding 'inputValue' option in the renderGrid macro with:
```
inputName: oro_datagrid_build_inputname(datagrid.name) ~ (datagrid.scope | length > 0 ? ':' ~ datagrid.scope : '')
```

**Comment by Grygir** [comment] 2016-02-18 10:32
The issue is fixed in master branch.

**Closed by Grygir** 2016-02-18 10:32 UTC
