### ISSUE TITLE
Exception in oro:entity-extend:cache:warmup

### ISSUE THREAD

**Issue by stalxed** [orocrm/platform#287] opened 2015-07-12 11:09 UTC
I found this in log of php:

```
[12:00:02 Europe/Moscow] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Property Oro\Bundle\EmailBundle\Entity\Email::$user_d41b1c4b does not exist' in C:\ZendServer\project\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\RuntimeReflectionService.php:82
Stack trace:
#0 C:\ZendServer\project\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\RuntimeReflectionService.php(82): ReflectionProperty->__construct('Oro\\Bundle\\Emai...', 'user_d41b1c4b')
#1 C:\ZendServer\project\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataInfo.php(899): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty('Oro\\Bundle\\Emai...', 'user_d41b1c4b')
#2 C:\ZendServer\project\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(537): Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection(Object(Doctrine\Common\Persistence\Mapping\RuntimeReflectionService))
#3 C:\ZendServer\project\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMe in C:\ZendServer\project\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\RuntimeReflectionService.php on line 82
```

I started investigating.

This error was repeated in: Windows Server 2012 R2, Ubuntu 14.04.
SO, this error is platform-independent.

It occurs in the generation of the cache. 
No matter how generated cache:
- rm -rf app/cache/\* and first access to web site
- or
-  php app/console cache:clear --env=prod

Error occurs in both cases at the time of generation of the cache.

I have made a complete log in the location of the exception and noticed following in global array $_SERVER:

``` php
  ["argv"]=>
  array(4) {
    [0]=>
    string(35) "C:/ZendServer/project/app/console"
    [1]=>
    string(30) "oro:entity-extend:cache:warmup"
    [2]=>
    string(5) "--env"
    [3]=>
    string(4) "prod"
  }
  ["argc"]=>
  int(4)
```

Generation of cache calls this script, the script of oro platform. And in it there is exception.  The script fails because of an exception.

It seems to me that the update cache somewhere confused order of call scripts.

**Comment by vsoroka** [comment] 2015-07-20 03:14
Hello @stalxed,

On which version of the platform do you reproduce this exception?
We did a lot of work to fix such problems in the latest master.

**Comment by stalxed** [comment] 2015-07-27 10:13
Hello @vsoroka!

Sorry for the delay in response.

I test this bug using clear installation from here:
http://www.orocrm.com/previous-versions/the-oro-platform-1-7-4

So latest version have this bug too(first post i write using oro platfrom 1.7.0).

**Comment by sagikazarmark** [comment] 2016-04-01 17:48
The exact same issue is happening to me:

`Property Oro\Bundle\EmailBundle\Entity\Email::$user_d41b1c4b does not exist`

My ORO version is 1.9. The interesting thing is that it only happens in production mode, and only for every first cache clear.

Here is what I tried so far (the list will grow as I try new things, because it is currently a blocker for our application, we can't make it work in production environment):

- Cache clear
- Manual cache directory removal
- Platform update

I would consider this a high prio bug, although the causes are not yet clear otherwise I guess you would have already found it.

**Comment by sagikazarmark** [comment] 2016-04-01 18:12
For some reasons, this relation is added to the Email entity:

```
'user_d41b1c4b' =>
  array(20) {
    'fieldName' =>
    string(13) "user_d41b1c4b"
    'targetEntity' =>
    string(33) "Oro\Bundle\UserBundle\Entity\User"
    'joinTable' =>
    array(3) {
      'name' =>
      string(30) "oro_rel_265353702da17977bb66fd"
      'joinColumns' =>
      array(1) {
        ...
      }
      'inverseJoinColumns' =>
      array(1) {
        ...
      }
    }
    'type' =>
    int(8)
    'mappedBy' =>
    NULL
    'inversedBy' =>
    NULL
    'isOwningSide' =>
    bool(true)
    'sourceEntity' =>
    string(35) "Oro\Bundle\EmailBundle\Entity\Email"
    'fetch' =>
    int(2)
    'cascade' =>
    array(0) {
    }
    'isCascadeRemove' =>
    bool(false)
    'isCascadePersist' =>
    bool(false)
    'isCascadeRefresh' =>
    bool(false)
    'isCascadeMerge' =>
    bool(false)
    'isCascadeDetach' =>
    bool(false)
    'joinTableColumns' =>
    array(2) {
      [0] =>
      string(8) "email_id"
      [1] =>
      string(7) "user_id"
    }
    'isOnDeleteCascade' =>
    bool(true)
    'relationToSourceKeyColumns' =>
    array(1) {
      'email_id' =>
      string(2) "id"
    }
    'relationToTargetKeyColumns' =>
    array(1) {
      'user_id' =>
      string(2) "id"
    }
    'orphanRemoval' =>
    bool(false)
  }
```

**Comment by sagikazarmark** [comment] 2016-04-01 18:36
Looking at the generated extend proxies: that email entity has the given user field.

**Comment by sagikazarmark** [comment] 2016-04-01 18:38
Related #199

**Comment by sagikazarmark** [comment] 2016-04-01 22:40
Further looking at this: I think I learned how the Extend bundle works :wink: 

Anyway, not sure where this thing fails. It seems that the extend configuration works fine, the generated proxy is correctly aliased.

**Comment by sagikazarmark** [comment] 2016-04-02 07:25
Steps to reproduce (you need docker and docker-compose):

``` bash
git clone https://github.com/webplates/platform-standard
cd platform-standard
composer install --ignore-platform-reqs
mkdir var/docker
docker-compose up -d
etc/docker/bin/init # This installs dev env as well, only execute the basic install if you don't need test
docker-compose run php bin/console cache:clear --env=prod --no-warmup
```

If the issue does not happen, rerun the cache clear, but in my tests, the error always occurred first.

**Comment by sagikazarmark** [comment] 2016-04-03 11:04
Interesting news: The issue only persists in production mode with the `--no-warmup` switch.

**Comment by sagikazarmark** [comment] 2016-04-03 18:41
I think I was finally able to trace the problem and find kind of a solution, although I am still unsure why this problem only persists during prod cache actions.

The problem occurs in the ProxyCache warmer. It seems that in production environment entity aliases are not loaded before the ProxyCache warmer starts working. (It is called even if the cache command is invoked with `--no-warmup`, because the container must be initialized in order to run cache cleaners.)

Entity aliases are loaded in the [EntityExtendBundle](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EntityExtendBundle/OroEntityExtendBundle.php#L157). However, if no aliases exists by the time the bundles are loaded, then no aliases gets loaded. Again, I am still unsure why this happens in prod, but not in dev.

My temporary solution is adding `ExtendClassLoadingUtils::setAliases($cacheDir);` in the end of [EntityCache warmer](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EntityExtendBundle/Cache/EntityCacheWarmer.php#L44). It is called before the ProxyCache warmer, but after the aliases are fully generated. Since the alias loader is idempotent, there is no risk in calling it twice. (The semi-temporary solution of mine will be adding a separate warmer after the EntityCache, but before the ProxyCache).

Although this solves the problem, it is still unclear why this happens in prod, but not in dev. Probably more investigation is necessary, but I think it is a good start.

**Comment by sagikazarmark** [comment] 2016-04-05 14:02
ping @vsoroka

**Comment by iklymenko** [comment] 2016-04-13 15:30
Hi @sagikazarmark,
sorry for a huge delay with an answer. We tried to find quick solution but seems that the issue is more complex that we expected. We will investigate it during next week and will provide you the results here! Thanks for your patience.

**Comment by sagikazarmark** [comment] 2016-04-13 15:32
Hi @iklymenko 

Thanks for letting me know. Yeah, it is pretty complex, it took me two days to end up with the results above.

Here is my temporary solution for the problem:

https://github.com/webplates/platform-standard/tree/master/src/HotfixBundle

**Comment by iklymenko** [comment] 2016-04-13 15:38
@sagikazarmark, thanks we will check it also!

**Comment by alex-n-2k7** [comment] 2016-04-19 11:53
Hi, @sagikazarmark 

I've been trying to reproduce your issue but couldn't (
I've tested with version 1.9 of platform on OsX and Fedora23(Redhat) with php version 5.5.34 and 5.6, the both environments were x64
I've also checked yours STRs with docker (with HotFix bundle and without it) but the result was the same - i never saw the exception.

And without possibility to reproduce it's very difficult to help. 
The same situation with the issue https://github.com/orocrm/platform/issues/434

So, it looks like platform dependent issue. 
Can you describe your environment? I think this could help.
Or the better it will be some VirtualBox image where the issue will be reproducible in stable way.

**Comment by sagikazarmark** [comment] 2016-04-22 19:38
Hi @alex-n-2k7 

I am going to try to create a little bit more separated environment (like virtualbox), although Docker should be kind of enough IMO. (Also, I tried it on OSX and Arch with PHP 5.5.x and 5.6 as well)

**Comment by artml** [comment] 2016-08-05 14:19
@sagikazarmark have you managed to reproduce this issue?

**Comment by turboezh** [comment] 2016-08-05 16:02
Hi. Maybe PR #278 would help somehow. But it was a long ago and I'm not sure about how it relates to this.

**Comment by sagikazarmark** [comment] 2016-08-06 10:54
I continuously have this issue in the described environment without the fix I applied. I will try to update the platform to a newer version to see if the issue is still there.

**Comment by sagikazarmark** [comment] 2016-08-19 13:19
After updating to 1.10.0 I still experience this issue. I have modified the above commands to be run in a dockerized environment, so it is COMPLETELY isolated. You need docker and docker compose:

``` bash
git clone https://github.com/webplates/platform-standard platform-issue287
cd platform-issue287
mkdir -p var/docker
docker-compose up -d
docker-compose run app composer install --no-interaction
sed -e '16,21d' -i src/HotfixBundle/Resources/config/services.yml # Removes the fix
docker-compose run app make setup
docker-compose run app bin/console cache:clear --env=prod --no-warmup # Suceeds
docker-compose run app bin/console cache:clear --env=prod --no-warmup # Fails
```

Result:

```
Fatal error: Uncaught ReflectionException: Property Oro\Bundle\EmailBundle\Entity\Email::$user_d41b1c4b does not exist in /app/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80
Stack trace:
#0 /app/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(80): ReflectionProperty->__construct('Oro\\Bundle\\Emai...', 'user_d41b1c4b')
#1 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(965): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty('Oro\\Bundle\\Emai...', 'user_d41b1c4b')
#2 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(721): Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection(Object(Doctrine\Common\Persistence\Mapping\RuntimeReflectionService))
#3 /app/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(343): Doctrine\ORM\Mapping\ClassMetadataFactory->wakeupReflection(Object(Doctrine\ORM\Mapping\ClassMeta in /app/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 80
```

Cleanup:
``` bash
docker-compose kill
docker-compose rm -f
cd ..
sudo rm -rf platform-issue287
```

Although the application is initially installed in dev mode, I tried the above commands in prod mode as well, I received the same result. In this case the commands are a little bit different:

``` bash
git clone https://github.com/webplates/platform-standard platform-issue287
cd platform-issue287
mkdir -p var/docker
docker-compose up -d
docker-compose run -e SYMFONY_ENV=prod app composer install --no-interaction
sed -i 's/database_host: 127.0.0.1/database_host: db/g' app/config/parameters.yml
sed -e '16,21d' -i src/HotfixBundle/Resources/config/services.yml # Removes the fix
docker-compose run app bin/console cache:clear --env=prod # Extra cache clear to rebuild container
docker-compose run -e SYMFONY_ENV=prod app make setup
docker-compose run app bin/console cache:clear --env=prod --no-warmup # Suceeds
docker-compose run app bin/console cache:clear --env=prod --no-warmup # Fails
```

I generally think that the cache warmer/listener priority should be checked in platform, because at the moment it relies on natural order which is not always a good idea (like in this case).

**Comment by mkudelya** [comment] 2017-01-24 14:46
Hi @sagikazarmark 

Sorry for long delay. I have tried ran your docker commands, but "docker-compose run app make setup" produced this error:

> ERROR - Set the "date.timezone" setting in php.ini* (like Europe/Paris).

Could you provide me your docker logs ? (stdout)
Also i didn't find 'platform-issue287' branch.

**Comment by RocKordier** [comment] 2017-01-24 17:36
Hey @mkudelya 
platform-issue287 isn't a branch. Its the target folder of the git clone command, i think. :)

**Comment by mkudelya** [comment] 2017-01-24 18:51
@RocKordier, you are right :)

**Comment by mkudelya** [comment] 2017-02-24 08:23
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.

**Closed by mkudelya** 2017-02-24 08:23 UTC
Labels: bug, open for contribution

**Comment by sagikazarmark** [comment] 2017-02-24 08:51
The reason why it became inactive is that I don't really use Oro anymore. Not particularly because of this issue.

That said, this is still an issue. I even mentioned my suspicion that the problem is caused by the order of event listeners. Up to you if you want to handle it.

**Comment by sergeyz** [comment] 2017-02-27 00:22
The issue is related to https://github.com/laboro/dev/commit/31ac0de8b48581875c4c886e2dcd7c0035c66039 I think, so should be fixed now
