### ISSUE TITLE
Google maps not showing in contacts

### ISSUE THREAD

**Issue by adbeliveau** [orocrm/platform#581] opened 2016-12-10 01:25 UTC
where do we insert the API keys ? I have a google account with an active api key and I have set up the Auth in system configuration.  how ever I get this error 

js?v=3.exp&sensor=false&libraries=weather&callback=google.loader.callbacks.maps:37 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

what am I missing ?

**Comment by sadortun** [comment] 2016-12-10 07:41
Duplicate of #526 and #381

**Comment by adbeliveau** [comment] 2016-12-11 01:01
Sorry Sadortun but #381 is an issue with Problem with country of Contacts NOT on how to make the google api work. Also #526 again is not how to make the google maps work in contacts but that the googlemaps.jps needs to be updated.

if you can please offer a solution to my problem that would be great, because the other two offer no solution to the underlying problem of HOW TO MAKE THE GOOGLE MAPS SHOW UP IN THE CONTACTS.

**Comment by sadortun** [comment] 2016-12-11 04:47
#526 will fix your problem by adding a configurable propriety in the configuration.

Meanwhile, you can hardcode it at your own risk  in `vendor\oro\platform\src\Oro\Bundle\AddressBundle\Resources\public\js\mapservice\googlemaps.js`

```js
    return Backbone.View.extend({
        options: {
            mapOptions: {
                zoom: 17,
                mapTypeControl: true,
                panControl: false,
                zoomControl: true
            },
            apiVersion: '3.exp',
            sensor: false,
            apiKey: "your Google Maps API Key here",
            showWeather: true
        },
```

**Comment by adbeliveau** [comment] 2016-12-11 23:39
Thank you for your reply, how ever I entered my api key and I sill get the apikey missing error.  there are 2 googlemaps.js  and I did it in both of them

**Comment by sadortun** [comment] 2016-12-11 23:40
Did you run oro:platform:update ? Or reinstalled the assets if you are not using symlinks?

**Comment by adbeliveau** [comment] 2016-12-11 23:42
i am new to this, no I did not ... i am using composer. ill try oro:platform:update. do i run it from a particular folder or from the main directory

**Comment by sadortun** [comment] 2016-12-12 00:16
Sorry, can't help you much..... did you put your key in quotes `"`

**Comment by adbeliveau** [comment] 2016-12-12 00:17
i did not the first time, i am updating now with the ""

**Comment by adbeliveau** [comment] 2016-12-12 00:34
thanks for the help IT WORKED. now i have to figure out how to add a configurable propriety in the configuration.... dont now code so it will be a challenge.

**Comment by sadortun** [comment] 2016-12-12 02:21
You can wait for #526 which will be fixed in 2.0 that should be released soon. :fireworks:

**Comment by artml** [comment] 2016-12-20 12:05
Just FYI: We might have some trouble with releasing this fix within 2.0, and it could be postponed to later maintenance versions

**Comment by mkudelya** [comment] 2017-02-14 10:51
Duplicate of #381. I'm closing it. Feel free open it if you have any question.

**Closed by mkudelya** 2017-02-14 10:51 UTC
Labels: bug, duplicate

**Comment by kusgpt26** [comment] 2017-08-16 02:05
Hi @mkudelya , 

I am facing same problem that  google map is not showing. I have an installation of OROCRM 2.0. 
When i put google api key 
 here `vendor\oro\platform\src\Oro\Bundle\AddressBundle\Resources\public\js\mapservice\googlemaps.js`  than it work properly but when override `AddressBundle`  than it did not pick changes.

I also run these command after overriding bundle-

```
php app/console assets:install
php app/coonsole assetic:dump
php app/console oro:requirejs:build
```
Please reply how i solve this problem.
