### ISSUE TITLE
Default value datagrid doesn't work

### ISSUE THREAD

**Issue by souhirBen** [orocrm/platform#404] opened 2016-02-29 16:13 UTC
Hi,

I'm trying to use a default value in my datagrid but it doesn't work. It works only after I click in options -> discard changes (the link next to the Title).

```yml
datagrid:
    example-grid:
        filters:
            default:
                datetime-field:
                    value:
                        start: '2015-02-01'
                        end: '{{2}}' 
                     type: %oro_filter.form.type.filter.datetime_range.class%::TYPE_BETWEEN

```

**Comment by sergeyz** [comment] 2016-02-29 16:30
Hi, @souhirBen !

please try next keys

```
                    value:
                        date_start: '2015-02-01'
                        date_end: '{{2}}' 
```

from https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/FilterBundle/Filter/AbstractDateFilter.php#L37-L38

**Comment by souhirBen** [comment] 2016-02-29 16:42
Hi @sergeyz  I tried it doesn't  work. I tried also with string value to be sure it doesn't work.

**Comment by sergeyz** [comment] 2016-02-29 20:55
I can confirm that default filter is not applied, thanks for your report!

**Comment by lmeliberty** [comment] 2016-04-19 11:57
Hello, 

Do you have news to fix this problem ? 
I've the same problem and it's not possible for the momment to update my project for my client.

Thanks

**Comment by iklymenko** [comment] 2016-04-20 07:11
Hi @lmeliberty,
since we have already several concerns related to this issue we will work on during next 2 weeks and include fix in the closest release. Thanks for your patience.

**Comment by lmeliberty** [comment] 2016-04-20 07:38
Hi @iklymenko,

Great, thanks for your reply.

**Comment by sergeyz** [comment] 2016-06-29 14:09
Hi! Fixed in 1.7-1.9 branches and master https://github.com/orocrm/platform/commit/0156e977fe0abb8b57717489408448788024a4e9

**Closed** 2016-06-29 14:10 UTC
